version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "npm"
    schedule:
      interval: "daily"
    directories:
      - "/CDK"
    groups:
      minor-and-patch:
        applies-to: security-updates
        update-types:
          - "patch"
  - package-ecosystem: "npm"
    schedule:
      interval: "daily"
    directories:
      - "/client"
    ignore:
      - dependency-name: "typescript"
        versions: [ ">=5.5.0" ]
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "@angular*"
        update-types:
          - "minor"
          - "patch"
      minor-and-patch:
        applies-to: version-updates
        exclude-patterns:
          - "@angular*"
        update-types:
          - "patch"
          - "minor"