micronaut:
  security:
    oauth2:
      enabled: false
    token:
      jwt:
        enabled: false
  server:
    cors:
      enabled: true
      configurations:
        ui:
          allowed-origins:
            - http://localhost:8080
            - http://localhost:4200

aws:
  secret-key: 123
  access-key-id: 123
  region: "eu-west-1"
  services:
    dynamodb:
      endpoint-override: "http://${DYNAMODB_DOMAIN:localhost}:4566"

endpoints:
  routes:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false

mockAuthConfig:
  sessionLessStateAuth: ${STATELESS_SESSION_AUTH:true}
  admin: ${IS_ADMIN:true}

dynamodb-tables:
  primary_table:
    table-name: primary_table
  order-table:
    table-name: order_table

langchain4j:
  open-ai:
    enabled: false

mockTextToMenuItemConfig:
  error: ${MOCK_TEXT_TO_MENU_ITEM_ERROR:false}