micronaut:
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:vRuiEfCobPOLacpjeRh4AOrFtWEuWs89VMQpoVucYX0dLVuksidTuE1TrGhjbNah}

aws:
  secret-key: 123
  access-key-id: 123
  region: "eu-west-1"
  services:
    dynamodb:
      endpoint-override: "http://${DYNAMODB_DOMAIN:localhost}:4566"

mockAuthConfig:
  sessionLessStateAuth: ${STATELESS_SESSION_AUTH:true}
  admin: ${IS_ADMIN:true}

dynamodb-tables:
  primary_table:
    table-name: primary_table
  order-table:
    table-name: order_table

langchain4j:
  open-ai:
    enabled: false