micronaut:
  deserialization:
    readDateTimestampsAsNanoseconds: false
    READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
  server:
    cors:
      enabled: true
      configurations:
        ui:
          allowed-origins:
            - http://localhost:8080
            - http://localhost:4200
  dynamodb:
    primary_table:
      region: "eu-west-1"
      endpoint: "http://${DYNAMODB_DOMAIN:localhost}:4566"

endpoints:
  routes:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
jackson:
  deserialization:
    readDateTimestampsAsNanoseconds: false
    READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
  serialization:
    WRITE_DATE_TIMESTAMP_AS_NANOSECONDS: false
  serialization-inclusion: always

mockAuthConfig:
  sessionLessStateAuth: ${stateless-session-auth:true}