micronaut:
  application:
    name: api
  serde:
    numeric-time-unit: milliseconds
    time-write-shape: integer

  security:
    authentication: cookie
    oauth2:
      clients:
        auth0:
          client-id: '${OAUTH_CLIENT_ID}'
          client-secret: '${OAUTH_CLIENT_SECRET}'
          openid:
            issuer: 'https://${OAUTH_DOMAIN}/'
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:vRuiEfCobPOLacpjeRh4AOrFtWEuWs89VMQpoVucYX0dLVuksidTuE1TrGhjbNah}

    endpoints:
      logout:
        get-allowed: true

  deserialization:
    readDateTimestampsAsNanoseconds: false
    READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
