micronaut:
  server:
    cors:
      enabled: false
  security:
    oauth2:
      enabled: false

endpoints:
  routes:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false

aws:
  secret-key: 123
  access-key-id: 123
  region: "eu-west-1"
  services:
    dynamodb:
      endpoint-override: "http://${DYNAMODB_DOMAIN:localhost}:4566"

mockAuthConfig:
  sessionLessStateAuth: ${STATELESS_SESSION_AUTH:true}
  admin: ${IS_ADMIN:true}