micronaut:
  server:
    cors:
      enabled: true
      configurations:
        ui:
          allowed-origins:
            - http://localhost:8080
            - http://localhost:4200
  security:
    redirect:
      login-success: http://localhost:4200/login-success

endpoints:
  routes:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false

dynamodb-tables:
  primary_table:
    table-name: primary_table
  order-table:
    table-name: order_table
