micronaut:
  server:
    cors:
      enabled: true
      configurations:
        ui:
          allowed-origins:
            - http://localhost:8080
            - http://localhost:4200
  security:
    redirect:
      login-success: http://localhost:4200/login-success

endpoints:
  routes:
    enabled: true
    sensitive: falses
  beans:
    enabled: true
    sensitive: false

aws:
  secret-key: 123
  access-key-id: 123
  region: "eu-west-1"
  services:
    dynamodb:
      endpoint-override: "http://${DYNAMODB_DOMAIN:localhost}:4566"

dynamodb-tables:
  primary_table:
    table-name: primary_table
  order-table:
    table-name: order_table
