micronaut:
  server:
    cors:
      enabled: false
  security:
    oauth2:
      enabled: false

endpoints:
  routes:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false

mockAuthConfig:
  sessionLessStateAuth: ${STATELESS_SESSION_AUTH:true}
  admin: ${IS_ADMIN:true}