aws:
  secret-key: 123
  access-key-id: 123
  region: "eu-west-1"
  services:
    dynamodb:
      endpoint-override: "http://${DYNAMODB_DOMAIN:localhost}:4566"

dynamodb-tables:
  primary_table:
    table-name: primary_table
  order-table:
    table-name: order_table
