micronaut:
  server:
    cors:
      enabled: false
  security:
    oauth2:
      enabled: false

dynamodb-tables:
  primary_table:
    table-name: ${PRIMARY_TABLE_NAME}
  order-table:
    table-name: ${ORDER_TABLE_NAME}
