name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  client-unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci

      - name: Build
        run: npm run build
  gradle:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Start local stack
        run: docker-compose up -d localstack

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Wait for localstack init script to finish
        run: bash scripts/wait_for_localstack_init_script_to_finish.sh

      - name: Run integration test
        run: ./gradlew integrationTest
  client-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Build Server Image
        run: ./gradlew dockerBuild

      - name: Run food-order-server container
        run: docker compose up -d food-order-server

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json

      - name: Install dependencies
        run: npm --prefix ./client ci

      - name: Wait for localstack init script to finish
        run: bash scripts/wait_for_localstack_init_script_to_finish.sh

      - name: Run E2E tests
        run: npm --prefix ./client run e2e

      - name: Dump localstack logs
        if: failure()
        run: docker logs localstack

      - name: Dump food-order-server logs
        if: failure()
        run: docker logs food-order-server
