name: Publish To Docker Hub

on:
  push:
    branches:
      - release/*
  pull_request:
    branches:
      - release/*

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Build Server Image
        run: ./gradlew dockerBuild

      - name: Docker Tag Server
        run: docker tag sharedfoodorder:latest thebotmeek/food_order_app

      - name: Build client image
        run: docker build ./client

      - name: Docker Tag Server
        run: docker tag foodorderclient:latest thebotmeek/food_order_client

      - name: Log in to Docker Hub
        uses: docker/login-action@7ca345011ac4304463197fac0e56eab1bc7e6af0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_KEY }}

      - name: Docker Push Server
        run: docker push thebotmeek/food_order_app

      - name: Docker Push Client
        run: docker push thebotmeek/food_order_client
