name: Publish Server Image To Docker Hub

on:
  push:
    branches: ['main']
    paths: ['server/**']

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew api:build --no-daemon

      - name: Run tests
        run: ./gradlew api:test --no-daemon

      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Log in to Docker Hub
        uses: docker/login-action@ef38ec311a7df3f01475313e7c5bb584b74b112a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build Server Image
        run: ./gradlew api:dockerfile

      - name: Build and push server image
        uses: docker/build-push-action@v6
        with:
          context: ./server/build/docker/main
          push: true
          tags: thebotmeek/food_order_app