name: Publish Client Image To Docker Hub

on:
  push:
    branches: ['main']
    paths: ['client/**']

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Log in to Docker Hub
        uses: docker/login-action@327cd5a69de6c009b9ce71bce8395f28e651bf99
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push client image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: thebotmeek/food_order_client
        env:
          GITHUB_ASSESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}