name: Publish To Docker Hub

on:
  push:
    branches:
      - release/*
  pull_request:
    branches:
      - release/*

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Log in to Docker Hub
        uses: docker/login-action@7ca345011ac4304463197fac0e56eab1bc7e6af0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build Server Image
        run: ./gradlew dockerfile

      - name: Build and push server image
        uses: docker/build-push-action@v6
        with:
          context: ./server/build/docker/main
          push: true
          tags: thebotmeek/food_order_app

      - name: Build and push client image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: thebotmeek/food_order_client