name: Publish To Docker Hub

on:
  push:
    branches:
      - release/*
  pull_request:
    branches:
      - release/*

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Build Server Image
        run: ./gradlew dockerBuild

      - name: Log in to Docker Hub
        uses: docker/login-action@1f36f5b7a2d2f7bfd524795fc966e6d88c37baa9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_KEY }}

      - name: Docker Tag
        run: docker tag sharedfoodorder:latest thebotmeek/food_order_app

      - name: Docker Push
        run: docker push thebotmeek/food_order_app
